# Generated by Django 4.0.4 on 2022-04-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_events_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.CharField(default=' datetime.date', max_length=700),
        ),
    ]
