# Generated by Django 4.0.4 on 2022-04-26 23:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_category_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='user_liked',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
