# Generated by Django 4.0.4 on 2022-04-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_likeuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='likeuser',
            name='user_liked',
            field=models.BooleanField(default=False),
        ),
    ]
