# Generated by Django 4.0.4 on 2022-04-27 01:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_likeuser_user_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='user_liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
