# Generated by Django 4.0.4 on 2022-04-27 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_events_user_liked_events_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeuser',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_events', to='api.events'),
        ),
    ]
